#!/usr/bin/env bash

set -e

function relink() {
  if [[ -h "$1" ]]; then
    echo "Relinking $1"
    rm "$1"
    ln -snf "$2" "$1"
  elif [[ -e "$1" ]]; then
    echo "Backing up $1"
    mv -n "$1" "$1.old"
    ln -snf "$2" "$1"
  else
    echo "Linking $1"
    ln -snf "$2" "$1"
  fi
}

echo "--- Linking files ---"

cd ~
relink .gitconfig ~/.dotfiles/git-config
relink .gitignore ~/.dotfiles/git-ignore-global
relink bin ~/.dotfiles/bin
relink .vimrc ~/.dotfiles/vimrc
relink .npmrc ~/.dotfiles/npmrc
relink .allowedsigners ~/.dotfiles/allowedsigners

# ---- Homebrew ----

echo "☕ Installing Homebrew"
if ! command -v brew &> /dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
  chmod -R go-w "$(brew --prefix)/share"
else
  echo "Homebrew already installed"
fi

echo "☕ Installing brew apps"
brew install git gh gpg vim wget ack tree highlight zsh-autosuggestions zsh-syntax-highlighting

# Install oh-my-zsh
echo "☕ Installing oh-my-zsh"
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
  echo "oh-my-zsh already installed"
fi

relink .bash_profile ~/.dotfiles/bash_profile
relink .bashrc ~/.dotfiles/bashrc
relink .zshrc ~/.dotfiles/zshrc
source ~/.zshrc

# Download and install fonts
echo "☕ Installing fonts from: https://github.com/romkatv/powerlevel10k#get-started"
curl -fLo "$HOME/Library/Fonts/MesloLGS NF Regular.ttf" https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
curl -fLo "$HOME/Library/Fonts/MesloLGS NF Bold.ttf" https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
curl -fLo "$HOME/Library/Fonts/MesloLGS NF Italic.ttf" https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
curl -fLo "$HOME/Library/Fonts/MesloLGS NF Bold Italic.ttf" https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf

echo "☕ Installing powerlevel theme, p10k"
if [ ! -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k" ]; then
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
else
  echo "powerlevel10k already installed"
fi
echo "☕ restart terminal to configure the p10k theme"

# ---- GPG ----

mkdir -p ~/.gnupg
cd ~/.gnupg
relink gpg.conf ~/.dotfiles/gpgconf
relink gpg-agent.conf ~/.dotfiles/gpgagentconf

chown -R $(whoami) ~/.gnupg/
chmod 600 ~/.gnupg/*
chmod 700 ~/.gnupg

# ---- Volta ----

echo "☕ Installing Volta"
if ! command -v volta &> /dev/null; then
  curl https://get.volta.sh | bash
  volta install node
else
  echo "Volta already installed"
fi

# --- SSH ---

echo "☕ Setting up SSH"
GIT_EMAIL=$(git config user.email)

if [ ! -f ~/.ssh/id_ed25519 ]; then
  echo "☕ No ssh key found, generating one"
  ssh-keygen -t ed25519 -C "$GIT_EMAIL"
fi
echo "☕ Starting ssh-agent"
eval "$(ssh-agent -s)"
echo "☕ Adding ssh key to ssh-agent"
ssh-add --apple-use-keychain ~/.ssh/id_ed25519

echo "$GIT_EMAIL $(cat ~/.ssh/id_ed25519.pub | cut -d ' ' -f 2)" > ~/.dotfiles/allowedsigners

echo "Host github.com
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519" > ~/.ssh/config

gh auth login --hostname github.com

echo "☕ Adding ssh key to GitHub account"
gh ssh-key add ~/.ssh/id_ed25519.pub --title "dotfiles"

echo "☕ Refreshing GitHub login with ssh key"
GH_TOKEN=$(cat ~/.ssh/id_ed25519)
gh auth refresh --hostname github.com

# ---- VIM ----
echo "☕ Setting vim plugins"

# mkdir -p ~/.vim ~/.vim/autoload ~/.vim/bundle ~/.vim/colors && \
# curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

cd ~/.vim/bundle
git clone https://github.com/pangloss/vim-javascript.git
git clone https://github.com/airblade/vim-gitgutter.git
git clone https://github.com/scrooloose/nerdtree.git
git clone https://github.com/ntpeters/vim-better-whitespace.git
git clone https://github.com/bling/vim-airline
git clone https://github.com/editorconfig/editorconfig-vim

mkdir  $HOME/.vim/colors/
curl -LSso $HOME/.vim/colors/lucario.vim https://raw.githubusercontent.com/raphamorim/lucario/master/colors/lucario.vim

relink $HOME/.vim/colors/monokai.vim $HOME/.dotfiles/vim-colors/monokai.vim

echo "☕ ☕ ☕ Done! ☕ ☕ ☕"

cd $HOME
